#!/bin/bash

echo "Launching pre-commit hook..."

if [ "$(git config --get hooks.gitleaksenabled)" != "true" ]; then
     echo "Gitleaks pre-commit hook is disabled."
     exit 0
fi

# Define the operating system
OS="`uname`"
case $OS in
    'Linux' | 'Darwin')
        OS='Linux/Mac'
        ;;
    'MINGW'* | 'CYGWIN'* | 'MSYS'*)
        OS='Windows'
        ;;
    *)
        OS='Unknown'
        ;;
esac

# Checking for gitleaks
if ! command -v gitleaks >/dev/null 2>&1; then
    echo "Gitleaks is not installed. Attempting automatic installation..."
    if [ "$OS" = "Linux/Mac" ]; then
        go install github.com/zricethezav/gitleaks/v8@latest
    elif [ "$OS" = "Windows" ]; then
        echo "Attempting to install Gitleaks on Windows..."
        curl -L https://github.com/zricethezav/gitleaks/releases/download/v8.2.7/gitleaks_8.2.7_windows_x64.zip -o gitleaks.zip
        unzip gitleaks.zip gitleaks.exe
        mv gitleaks.exe /usr/local/bin
        rm gitleaks.zip
    else
        echo "Unsupported OS for automatic installation."
        exit 1
    fi
fi


# Start gitleaks
gitleaks detect --source="."
if [ $? -ne 0 ]; then
     echo "Gitleaks discovered potential secrets. Commit aborted."
     exit 1
fi

echo "Everything is fine"
exit 0