name: KBOT-CICD

on:
  push:
    branches:
      - 'develop'

permissions:
  contents: write

jobs:
  ci:
    name: Kbot CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run test
        env:
          TELE_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        run: make test

      - name: Docker Hub login
        uses: docker/login-action@v2
        permissions:
          packages: write
          contents: read
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.MY_GITHUB_TOKEN }}
        
      - name: Build&Push
        env:
          APP: "kbot"
          REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}
        run: make image push
  
  
  cd:
    name: Kbot CD
    needs: ci
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - uses: mikefarah/yq@master
      with:
        cmd: yq -i '.image.tag=strenv(VERSION)' helm/values.yaml

    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -am "update version $VERSION"
        git push

        